Repository galacticusorg/galacticus, pull requests merged in 2024-07, with the labels that each got.

#636 Avoid attempting to tabulate to zero magnification
  source/structure_formation.gravitational_lensing.Takahashi_2011.F90
Labels: bug, structure formation

#638 Improve the formatting of the tree output time messages
  source/tasks.evolve_forests.F90
Labels: minor

#639 Avoid segfault when evaluating delay time integrals
  source/stellar_astrophysics.supernovae_type_Ia.differential_delay_time_distribution.F90
  source/stellar_astrophysics.supernovae_type_Ia.mass_independent_delay_time_distribution.F90
  source/stellar_astrophysics.supernovae_type_Ia.power_law_delay_time_distribution.F90
Labels: bug, stellar populations

#637 Provide a more helpful error message when single epoch output is not allowed
  source/geometry.surveys.Baldry-2012-GAMA.F90
  source/geometry.surveys.Bernardi-2013-SDSS.F90
  source/geometry.surveys.Caputi-2011-UKIDSS-UDS.F90
  source/geometry.surveys.Davidzon-2013-VIPERS.F90
  source/geometry.surveys.Gunawardhana-2013-SDSS.F90
  source/geometry.surveys.Hearin-2014-SDSS.F90
  source/geometry.surveys.Kelvin-2014-GAMAnear.F90
  source/geometry.surveys.Li-White-2009-SDSS.F90
  source/geometry.surveys.Local_Group_DES.F90
  source/geometry.surveys.Local_Group_SDSS.F90
  source/geometry.surveys.Local_Group_classical.F90
  source/geometry.surveys.Martin-2010-ALFALFA.F90
  source/geometry.surveys.Montero-Dorta-2009-SDSS.F90
  source/geometry.surveys.Moustakas-2013-PRIMUS.F90
  source/geometry.surveys.Muzzin-2013-ULTRAVISTA.F90
  source/geometry.surveys.Tomczak-2014-ZFOURGE.F90
  source/output.analyses.utilities.F90
Labels: error handling

#641 Ensure that the step descriptor is initialized
  source/merger_trees.evolve.profiler.tiny_steps.F90
Labels: bug

#644 Allow specifying output times via the lookback time
  source/output.times.list.F90
  testSuite/parameters/test-output-times.xml
  testSuite/test-output-times.pl
Labels: enhancement

#645 Allow the minimum orbital distance recorded to be relative to the immediate or isolated host
  perl/Galacticus/Build/Components/TreeNodes.pm
  source/nodes.operators.physics.satellite.minimum_distance.F90
  source/objects.nodes.F90
Labels: satellites

#646 Provide a `nodeOperatorFiltered` class
  source/nodes.operators.filtered.F90
  source/nodes.operators.multi.F90
Labels: nodes

#647 Change the definition of dynamical timescale to follow that in Binney & Tremaine, "Galactic Dynamics".
  source/satellites.tidal_stripping.rate.Zentner2005.F90
  testSuite/parameters/idealizedSubhaloSimulations/tidalTrackBestFit_xc_0.7_ratio_0.005_alpha_1.0_beta_3.0_gamma_1.5.xml
  testSuite/parameters/idealizedSubhaloSimulations/tidalTrackBestFit_xc_0.7_ratio_0.01_alpha_1.0_beta_3.0_gamma_1.5.xml
  testSuite/parameters/idealizedSubhaloSimulations/tidalTrackBestFit_xc_0.7_ratio_0.05_alpha_1.0_beta_3.0_gamma_0.5.xml
  testSuite/parameters/idealizedSubhaloSimulations/tidalTrackBestFit_xc_0.7_ratio_0.05_alpha_1.0_beta_3.0_gamma_1.0.xml
  testSuite/parameters/idealizedSubhaloSimulations/tidalTrackBestFit_xc_0.7_ratio_0.2_alpha_1.0_beta_3.0_gamma_0.0.xml
  testSuite/parameters/idealizedSubhaloSimulations/tidalTrackBestFit_xc_0.7_ratio_0.2_alpha_1.0_beta_3.0_gamma_0.5.xml
  testSuite/parameters/idealizedSubhaloSimulations/tidalTrackBestFit_xc_0.7_ratio_0.2_alpha_1.0_beta_3.0_gamma_1.0.xml
  testSuite/parameters/idealizedSubhaloSimulations/tidalTrackBestFit_xc_0.7_ratio_0.4_alpha_1.0_beta_3.0_gamma_0.0.xml
Labels: bug, satellites

#649 Replace the `nodeOperatorGalaxyMergersOutput` class with `nodeOperatorGalaxyMergers`
  perl/Galacticus/Build/Components/Classes/MetaProperties.pm
  source/merger_trees.outputter.buffer_types.F90
  source/merger_trees.outputter.standard.F90
  source/nodes.operators.analyses.galaxy_mergers.F90
  source/nodes.operators.output.galaxy_mergers.F90
  source/nodes.property_extractor.galaxy_mergers.F90
  source/nodes.property_extractor.galaxy_mergers.indices.F90
  source/nodes.property_extractor.galaxy_mergers.physical.F90
  source/nodes.property_extractor.integer_list.F90
  source/nodes.property_extractor.multi.F90
  source/objects.nodes.F90
  source/utility.IO.HDF5.F90
Labels: IO, merging

#651 Allow filter-based labelling on post-evolution
  source/nodes.operators.metadata.label.F90
  source/nodes.property_extractor.tree_indices.F90
Labels: enhancement

#652 Implement missing calculation of beta-profile radial moment for radii of 0 and ∞
  source/mass_distributions.spherical.beta_profile.F90
  source/tests.mass_distributions.F90
Labels: mass distributions

#653 Add a helpful error message when integration of σ(M) fails
  source/structure_formation.cosmological_mass_variance.filtered_power_spectrum.F90
Labels: error handling

#654 Add a more helpful error message for invalid default class names
  perl/Galacticus/Build/SourceTree/Process/FunctionClass.pm
Labels: error handling, build

#655 Avoid thread conflicts when setting dark matter profile scales read from merger tree files
  source/merger_trees.construct.read.F90
Labels: bug

#656 Avoid segfaults when computing ram pressure forces
  parameters/reference/cosmologyMillennium.xml
  parameters/reference/darkMatterHalosStructureNBody.xml
  parameters/reference/evolutionGalaxyFormationNBody.xml
  parameters/reference/powerSpectrumMillennium.xml
  source/hot_halo.ram_pressure_force.relative_position.F90
Labels: bug

#657 Provide helpful messages when CIE file extrapolation types are invalid
  perl/Galacticus/Build/SourceTree/Process/Enumeration.pm
  source/chemical.state.CIE_file.F90
  source/cooling.cooling_function.CIE_file.F90
  source/input.paths.F90
Labels: error handling

#658 Support discovery and build of newly added source files
  Makefile
  scripts/build/codeDirectivesParse.pl
  scripts/build/moduleDependencies.pl
  scripts/build/useDependencies.pl
Labels: build
