Repository galacticusorg/galacticus, pull requests merged in 2024-08, with the labels that each got.

#659 Avoid deadlocks when reporting the location of the `datasets` repo
  source/atomic.data.F90
  source/instruments.filters.F90
  source/interface.Local_Group_database.F90
  source/objects.chemical_structure.F90
  source/stellar_astrophysics.supernovae_type_Ia.fixed_yield.F90
Labels: bug

#660 Correctly handle XML `XInclude` elements with absolute paths
  source/utility.IO.XML.F90
Labels: enhancement, IO

#661 Add functionality to output the mass profile at radii enclosing fractions of the satellite bound mass
  .github/workflows/cicd.yml
  source/galactic_structure.radius_definition.F90
  source/nodes.property_extractor.CGM_cooling_function.F90
  source/nodes.property_extractor.density.F90
  source/nodes.property_extractor.mass_profile.F90
  source/nodes.property_extractor.projected_density.F90
  source/nodes.property_extractor.projected_mass.F90
  source/nodes.property_extractor.rotation_curve.F90
  source/nodes.property_extractor.velocity_dispersion.F90
  testSuite/parameters/massProfileSatelliteBoundMass.xml
  testSuite/test-massProfileSatelliteBoundMass.py
Labels: enhancement, subhalos

#663 If running in a TTY an ASCII art logo is output
  source/display.banner.F90
Labels: enhancement, trivial

#664 Report the command line used on error
  source/error.F90
Labels: enhancement, error handling

#665 Correct description of disk velocity calculation for disk stability
  source/galactic_dynamics.bar_instability.Efstathiou1982.F90
Labels: documentation

#666 Enhance the `nodePropertyExtactorOutputSelector` class
  source/accretion_disks.spectra.file.F90
  source/nodes.property_extractor.output_selector.F90
  testSuite/parameters/outputSelector.xml
  testSuite/test-outputSelector.pl
Labels: enhancement, IO

#668 Enforce minimum time in lightcone output
  source/geometry.lightcones.F90
  source/geometry.lightcones.cylindrical.F90
  source/geometry.lightcones.null.F90
  source/geometry.lightcones.square.F90
  source/merger_trees.evolve.timesteps.lightcone_crossing.F90
Labels: bug, lightcones

#671 Provide more informative error messages when failing to parse radius specifiers
  source/galactic_structure.options.F90
  source/galactic_structure.radius_definition.F90
Labels: error handling

#670 Add stream_kick.F90 filter for stream velocity kick.
  source/galactic.filters.stream_kick.F90
Labels: subhalos

#673 Add a `nodeOperator` to assess the reliability of merger trees
  parameters/reference/cosmologyUNIT.xml
  parameters/reference/evolutionGalaxyFormationNBody.xml
  parameters/reference/powerSpectrumUNIT.xml
  parameters/reference/simulationUNIT.xml
  source/nodes.operators.analyses.assembly_history_heuristics.F90
  source/objects.nodes.labels.F90
Labels: merger trees, meta

#674 Add functionality for working with output times
  source/galactic.filters.output_times.F90
  source/merger_trees.construct.build.masses.union.F90
  source/output.times.list.F90
  source/output.times.uniform_spacing_in_time.F90
  source/output.times.union.F90
Labels: enhancement

#675 Port the script used to extract single merger trees from file to Python
  scripts/aux/extractSingleTree.pl
  scripts/aux/extractSingleTree.py
  source/tasks.merger_tree_file_builder.F90
  testSuite/parameters/extractSingleTreeRun.xml
  testSuite/test-Millennium-tree-builder.pl
Labels: merger trees

#676 Set the vector angular momentum (if possible) in the `nodeOperatorHaloAngularMomentumRandom` class
  source/nodes.operators.physics.halo_angular_momentum_random.F90
Labels: bug

#680 Provide a more helpful error message when a parameter referenced in an expression is not found
  source/utility.input_parameters.F90
Labels: error handling

#682 Fix parallel tree build indexing
  source/merger_trees.construct.builder.Cole2000.F90
  source/merger_trees.construct.builder.Cole2000.parallel.F90
  source/merger_trees.evolver.threaded.F90
Labels: bug, OpenMP, merger trees

#684 Correctly set the final time for the star formation history
  source/star_formation.histories.adaptive.F90
Labels: star formation
