Repository galacticusorg/galacticus, pull requests merged in 2025-01, with the labels that each got.

#765 Fix sample grid state size for the `posteriorSamplesPriorGrid` class
  source/posterior_sampling.state.samples.prior_grid.F90
  source/utility.multi_counter.F90
Labels: bug, constraints

#767 Update Shen 2003 mass-size relation to reflect erratum
  source/output.analyses.mass_size_relation.Shen2003.F90
Labels: bug, trivial, constraints

#769 Ensure that the arrays used to store serialization offsets for meta-properties are of sufficient length
  perl/Galacticus/Build/Components/Implementations/ODESolver.pm
Labels: bug, major, build

#770 Fix issues in the normalization of log-likelihoods in `outputAnalysis` classes
  source/output.analyses.correlation_function.F90
  source/output.analyses.mean_function_1d.F90
  source/output.analyses.scatter_function_1d.F90
  source/output.analyses.stellar_vs_halo_mass_relation.COSMOS_Leauthaud2012.F90
  source/output.analyses.volume_function_1d.F90
Labels: bug, constraints

#771 Correct variable used in function call in the `virialOrbitWetzel2010` class
  source/satellites.merging.virial_orbits.Wetzel2010.F90
Labels: bug, satellites

#772 Add a timeout for file lock requests
  source/flock.c
  source/utility.files.F90
Labels: IO

#773 Add optional display of evaluation times in the `posteriorSampleLikelihoodGalaxyPopulation` class
  source/models.likelihoods.galaxy_population.F90
  source/posterior_sampling.simulation.differential_evolution.F90
Labels: constraints

#774 Remove an unused condition
  source/satellites.tidal_heating.rate.Gnedin1999.F90
Labels: trivial

#775 Add an abstract class which automates tabulation of parametric, spherically-symmetric, collisionless mass distributions
  .github/workflows/cicd.yml
  scripts/build/sourceDigests.pl
  source/kinematic_distributions.collisionless.tabulated.F90
  source/mass_distributions.F90
  source/mass_distributions.spherical.F90
  source/mass_distributions.spherical.cored_NFW.F90
  source/mass_distributions.spherical.tabulated.F90
  source/tests.mass_distributions.tabulated.F90
  source/utility.multi_counter.F90
Labels: mass distributions
